Repository googleapis/java-bigtable, pull requests merged in 2019-11, with the labels that each got.

#56 docs: cleanup links to java-bigtable and javadoc
  README.md
  google-cloud-bigtable/pom.xml
Labels: cla: yes

#59 fix: use proper scope for DirectPath transitive dependencies
  google-cloud-bigtable/pom.xml
Labels: cla: yes

#60 chore: update developer docs for testing
  CONTRIBUTING.md
  google-cloud-bigtable/pom.xml
  scripts/setup-test-table.sh
Labels: cla: yes

#67 fix: fix regression in batch#close silently ignoring entry failures by upgrading to gax to 1.50.0
  pom.xml
Labels: cla: yes

#69 fix: Prevent integration tests from different profiles from clobbering each other
  google-cloud-bigtable/pom.xml
  scripts/setup-test-table.sh
Labels: cla: yes, type: bug

#71 chore: release 1.7.1-SNAPSHOT
  google-cloud-bigtable-bom/pom.xml
  google-cloud-bigtable-emulator/pom.xml
  google-cloud-bigtable/pom.xml
  grpc-google-cloud-bigtable-admin-v2/pom.xml
  grpc-google-cloud-bigtable-v2/pom.xml
  pom.xml
  proto-google-cloud-bigtable-admin-v2/pom.xml
  proto-google-cloud-bigtable-v2/pom.xml
  versions.txt
Labels: cla: yes, type: process

#75 chore: fix tests for targeting test env
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java
Labels: cla: yes

#76 chore: ignore CONTRIBUTING.md in synthtool
  synth.py
Labels: cla: yes

#77 chore: allow prod test endpoint overrides separate from directpath
  google-cloud-bigtable/pom.xml
Labels: cla: yes

#78 chore: use zones that are available in all test envs
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
Labels: cla: yes

#82 chore: fix integration test zones to work across all environments
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
Labels: cla: yes

#80 chore: add a runnable tool that can we used to debug gRPC connection issues
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/misc_utilities/SimpleGceRawRead.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/misc_utilities/package-info.java
Labels: cla: yes

#79 chore: Ignore gapic settings for all streaming RPCs
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java
Labels: cla: yes

#81 chore: improve tests
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java
Labels: cla: yes

#83 chore: fix tests
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  pom.xml
Labels: cla: yes

#84 chore: update basicClusterOperationTest to be more robust
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/LargeRowIT.java
Labels: cla: yes

#89 chore: fix javadoc site after repo split
  google-cloud-bigtable-bom/pom.xml
  google-cloud-bigtable/pom.xml
  pom.xml
Labels: cla: yes

#91 chore: update Error message for bad bigtable.env variable
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java
Labels: cla: yes

#92 Added `FILTERS.timestamp().exact()` for better access & read ability.
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Filters.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java
Labels: cla: yes

#94 chore: make sure that integration tests only run as part of a profile
  google-cloud-bigtable/pom.xml
Labels: cla: yes
