Repository googleapis/java-bigtable, pull requests merged in 2020-09, with the labels that each got.

#398 feat: extend channel priming logic to also send fake requests
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RefreshChannel.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableChannelPrimer.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/RefreshChannelTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableChannelPrimerTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
Labels: api: bigtable, cla: yes

#407 fix: RowCells are not actually serializeable
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowCell.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/RowCellTest.java
Labels: api: bigtable, cla: yes

#410 fix: Add documentation to bulkReadRows that each batch will process t…
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
Labels: api: bigtable, cla: yes

#413 chore: update CODEOWNERS
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: bigtable, cla: yes

#416 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#417 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#397 fix: Filters should be serializable
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Filters.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java
Labels: api: bigtable, cla: yes

#430 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#429 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: bigtable, automerge, cla: yes

#433 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#435 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#436 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#438 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
