Repository googleapis/java-bigtable, pull requests merged in 2020-08, with the labels that each got.

#374 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#371 chore: Introspect peer IP address for directpath tests
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
Labels: cla: yes

#379 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: cla: yes, context: full

#381 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#376 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /bigtable/snippets
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  samples/snippets/src/main/java/com/example/bigtable/Filters.java
  samples/snippets/src/main/java/com/example/bigtable/Reads.java
  samples/snippets/src/main/java/com/example/bigtable/WriteBatch.java
  samples/snippets/src/main/java/com/example/bigtable/WriteConditionally.java
  samples/snippets/src/main/java/com/example/bigtable/WriteIncrement.java
  samples/snippets/src/main/java/com/example/bigtable/WriteSimple.java
  samples/snippets/src/test/java/com/example/bigtable/FiltersTest.java
  samples/snippets/src/test/java/com/example/bigtable/ReadsTest.java
  samples/snippets/src/test/java/com/example/bigtable/WritesTest.java
  synth.py
Labels: cla: yes

#375 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /bigtable
  samples/snippets/src/main/java/com/m/examples/bigtable/HelloWorld.java
  samples/snippets/src/main/java/com/m/examples/bigtable/InstanceAdminExample.java
  samples/snippets/src/main/java/com/m/examples/bigtable/Quickstart.java
  samples/snippets/src/main/java/com/m/examples/bigtable/TableAdminExample.java
  samples/snippets/src/test/java/com/m/examples/bigtable/HelloWorldTest.java
  samples/snippets/src/test/java/com/m/examples/bigtable/InstanceAdminExampleTest.java
  samples/snippets/src/test/java/com/m/examples/bigtable/QuickstartTest.java
  samples/snippets/src/test/java/com/m/examples/bigtable/TableAdminExampleTest.java
Labels: cla: yes

#393 chore: update build cfgs
  .github/workflows/samples.yaml
  synth.metadata
Labels: cla: yes, context: full

#388 chore(fix): directpath ipv4 connection should not fail for an ipv6-enabled test client
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
Labels: api: bigtable, cla: yes

#395 fix: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#396 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#350 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-bigtable/pom.xml
  grpc-google-cloud-bigtable-admin-v2/pom.xml
  grpc-google-cloud-bigtable-v2/pom.xml
  proto-google-cloud-bigtable-admin-v2/pom.xml
  proto-google-cloud-bigtable-v2/pom.xml
Labels: api: bigtable, cla: yes
