Repository googleapis/java-bigtable, pull requests merged in 2020-06, with the labels that each got.

#330 chore: specify primary CODEOWNERS team in repo-metadata
  .github/CODEOWNERS
  .repo-metadata.json
  synth.metadata
Labels: cla: yes

#331 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#333 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#335 Revert "fix: change app_profile_id to the correct header app_profile"
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/HeadersTest.java
Labels: cla: yes

#342 chore: set Ruby namespace in proto options
  proto-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/BigtableInstanceAdminProto.java
  proto-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/BigtableTableAdminProto.java
  proto-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/CommonProto.java
  proto-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/InstanceProto.java
  proto-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/TableProto.java
  proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/bigtable_instance_admin.proto
  proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/bigtable_table_admin.proto
  proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/common.proto
  proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/instance.proto
  proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/table.proto
  proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/BigtableProto.java
  proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/DataProto.java
  proto-google-cloud-bigtable-v2/src/main/proto/google/bigtable/v2/bigtable.proto
  proto-google-cloud-bigtable-v2/src/main/proto/google/bigtable/v2/data.proto
  synth.metadata
Labels: cla: yes, context: full

#346 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#351 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#355 ci: Revert "ci(java): run dependency test on Java 8 and 11 (#351)"
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes
