Repository googleapis/java-bigtable, pull requests merged in 2021-06, with the labels that each got.

#846 fix: revert conformance test version
  pom.xml
Labels: api: bigtable, cla: yes

#849 Revert "fix: revert conformance test version"
  pom.xml
Labels: api: bigtable, automerge, cla: yes

#853 chore(deps): gapic-generator-java v1.0.10
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BaseBigtableInstanceAdminClientTest.java
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#850 fix: Fix the race condition in decay average
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlStats.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlStatsTest.java
Labels: api: bigtable, cla: yes

#848 feat: promote stream wait timeouts to deadlines for point reads
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallable.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallableTest.java
Labels: api: bigtable, automerge, cla: yes

#854 deps: update truth-proto-extension to 1.1.3 and exclude protobuf-java…
  pom.xml
Labels: api: bigtable, cla: yes

#859 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#860 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#867 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#869 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#870 chore(deps): gapic-generator-java v1.0.11
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BaseBigtableInstanceAdminClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BaseBigtableTableAdminClientTest.java
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#873 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#872 chore: create flakybot.yaml
  .github/flakybot.yaml
Labels: api: bigtable, cla: yes

#861 feat: all setting timeouts for batchers + fix handling of timeouts for point reads
  google-cloud-bigtable/clirr-ignored-differences.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallable.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallableTest.java
Labels: api: bigtable, cla: yes

#875 revert: Revert "feat: all setting timeouts for batchers + fix handling of timeouts for point reads"
  google-cloud-bigtable/clirr-ignored-differences.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallable.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallableTest.java
Labels: api: bigtable, cla: yes

#876 revert: Revert "feat: promote stream wait timeouts to deadlines for point reads"
  google-cloud-bigtable/clirr-ignored-differences.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallable.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/PointReadTimeoutCallableTest.java
Labels: api: bigtable, automerge, cla: yes

#880 docs: fix connection pool size for samples
  samples/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
  samples/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
Labels: api: bigtable, automerge, cla: yes

#878 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#877 feat: call setting timeouts for batchers
  google-cloud-bigtable/clirr-ignored-differences.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/FakeServiceHelper.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
Labels: api: bigtable, cla: yes

#883 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#886 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#884 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full
