Repository googleapis/java-bigtable, pull requests merged in 2021-07, with the labels that each got.

#892 fix: jwt authentication on batch-bigtable.googleapis.com
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/JwtCredentialsWithAudience.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
Labels: api: bigtable, cla: yes

#894 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#897 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#898 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#900 chore: remove distributionManagement section
  google-cloud-bigtable-bom/pom.xml
  google-cloud-bigtable-deps-bom/pom.xml
Labels: api: bigtable, automerge, cla: yes

#901 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#903 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#904 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#879 chore: use BaseApiTracer and BaseApiTracerFactory
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracer.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/CompositeTracerFactory.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerFactory.java
Labels: api: bigtable, automerge, cla: yes

#914 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#913 chore: allow updating extra files in 1.22.0-sp branch
  .github/release-please.yml
Labels: api: bigtable, cla: yes

#915 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#916 fix: client.close() should wait until the channels are terminated before shutting down the executor
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubCloseRetryTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubCloseTest.java
Labels: api: bigtable, cla: yes

#920 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#922 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#925 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#927 ci: remove java 7 units check
  .github/sync-repo-settings.yaml
Labels: api: bigtable, automerge, cla: yes
