Repository googleapis/java-bigtable, pull requests merged in 2021-04, with the labels that each got.

#698 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, cla: yes

#656 feat: add CMEK Support
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClient.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Backup.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/Cluster.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequest.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/CreateInstanceRequest.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/EncryptionInfo.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/common/Status.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/BackupTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/ClusterTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/CreateClusterRequestTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/EncryptionInfoTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/common/StatusTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/EmulatorEnv.java
  pom.xml
Labels: api: bigtable, cla: yes

#706 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#708 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#702 test: small refactor to cmek test
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
Labels: api: bigtable, automerge, cla: yes

#697 samples: refactor Bigtable tests using a base class
  samples/snippets/src/main/java/com/example/bigtable/HelloWorld.java
  samples/snippets/src/main/java/com/example/bigtable/InstanceAdminExample.java
  samples/snippets/src/main/java/com/example/bigtable/Quickstart.java
  samples/snippets/src/main/java/com/example/bigtable/TableAdminExample.java
  samples/snippets/src/test/java/com/example/bigtable/BigtableBaseTest.java
  samples/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
  samples/snippets/src/test/java/com/example/bigtable/FiltersTest.java
  samples/snippets/src/test/java/com/example/bigtable/HelloWorldTest.java
  samples/snippets/src/test/java/com/example/bigtable/InstanceAdminExampleTest.java
  samples/snippets/src/test/java/com/example/bigtable/MobileTimeSeriesBaseTest.java
  samples/snippets/src/test/java/com/example/bigtable/QuickstartTest.java
  samples/snippets/src/test/java/com/example/bigtable/ReadsTest.java
  samples/snippets/src/test/java/com/example/bigtable/TableAdminExampleTest.java
  samples/snippets/src/test/java/com/example/bigtable/WritesTest.java
Labels: api: bigtable, cla: yes, samples

#711 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#709 chore: update DirectPath profiles
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/CloudEnv.java
Labels: api: bigtable, cla: yes

#712 test: update zones in cmek test
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
Labels: api: bigtable, cla: yes

#714 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#716 fix: change clusterId in Cmek test
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
Labels: api: bigtable, cla: yes

#719 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#722 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#724 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#725 chore: exclude autogenerated files from codecov
  codecov.yaml
  synth.py
Labels: api: bigtable, automerge, cla: yes

#726 chore: minor test cleanup
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataSettingsTest.java
Labels: api: bigtable, automerge, cla: yes

#721 feat: dynamic flow control
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettings.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlCallable.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlStats.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracer.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataSettingsTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BulkMutateIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/BigtableBatchingCallSettingsTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlCallableTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/DynamicFlowControlStatsTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettingsTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
Labels: api: bigtable, cla: yes

#715 chore: improve embedded version handling
  .github/release-please.yml
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/VersionTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
  synth.py
Labels: api: bigtable, automerge, cla: yes

#731 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#735 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#737 fix(docs): correct docs for CUSTOMER_MANAGED_ENCRYPTION
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/EncryptionInfo.java
Labels: api: bigtable, cla: yes

#740 chore: Re-generated to pick up changes from synthtool
  .github/release-please.yml
  .kokoro/build.sh
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  codecov.yaml
  synth.metadata
Labels: api: bigtable, cla: yes, context: partial

#742 chore: remove duplicate deps (error_prone & autovalue) from bigtable specific pom
  google-cloud-bigtable-deps-bom/pom.xml
  google-cloud-bigtable/EnableAutoValue.txt
  google-cloud-bigtable/pom.xml
  pom.xml
Labels: api: bigtable, automerge, cla: yes

#770 chore: update row merger
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/readrows/RowMerger.java
Labels: api: bigtable, cla: yes

#778 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#780 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#515 feat: allow restore backup to different instance
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/RestoreTableRequestTest.java
Labels: api: bigtable, automerge, cla: yes

#786 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#793 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes
