Repository googleapis/java-bigtable, pull requests merged in 2021-09, with the labels that each got.

#978 chore: re-generated to pick up changes from synthtool
  renovate.json
  synth.metadata
Labels: cla: yes, api: bigtable, context: partial

#981 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigtable, automerge

#983 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: bigtable, automerge, context: full

#985 chore: temporary workaround for maven wildcard excludes
  google-cloud-bigtable/pom.xml
Labels: cla: yes, api: bigtable, automerge

#987 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigtable, automerge

#984 refactor: Avoid setting empty builders in proto setters
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/MutationTest.java
Labels: cla: yes, api: bigtable

#989 revert: temporary workaround for maven wildcard excludes
  google-cloud-bigtable/pom.xml
Labels: cla: yes, api: bigtable, automerge

#992 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigtable, automerge

#994 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge

#998 chore: synthtool config changes
  .github/readme/synth.py
  .github/trusted-contribution.yml
  synth.metadata
Labels: cla: yes, api: bigtable, context: partial

#999 chore(java): update shared-config and shared-dependencies version in pom template
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: bigtable, context: full

#1001 build: use maven 3.8.1 for ci
  .github/workflows/ci.yaml
Labels: cla: yes, api: bigtable

#1000 fix: client.close() should wait until the channels are terminated bef…
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubCloseRetryTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubCloseTest.java
Labels: cla: yes, api: bigtable

#1004 fix: parallel execution and verbose grpc logs
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java
Labels: cla: yes, api: bigtable

#1005 chore: fix grpc logs part 2
  google-cloud-bigtable/pom.xml
Labels: cla: yes, api: bigtable, automerge

#1008 deps: migrate to mockito-core 3.12.4
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableInstanceAdminClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/stub/AwaitReplicationCallableTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/MutateRowCallableTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsFirstCallableTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsRetryTest.java
  pom.xml
Labels: cla: yes, api: bigtable

#1015 chore: update doclet version
  pom.xml
Labels: cla: yes, api: bigtable

#1024 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, api: bigtable, context: full

#1026 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigtable

#1025 chore: re-generated to pick up changes from synthtool
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, api: bigtable, automerge, context: full
