Repository googleapis/java-bigtable, pull requests merged in 2021-05, with the labels that each got.

#795 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: none

#794 chore: cloud-rad doc generation
  .kokoro/release/publish_javadoc11.sh
  pom.xml
Labels: api: bigtable, cla: yes

#787 fix: filter limit constant
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java
Labels: api: bigtable, cla: yes, type: bug

#801 chore(test): improve resource handling in tests
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BulkMutateIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
Labels: api: bigtable, cla: yes

#800 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigtable, cla: yes, context: partial

#804 docs: update the comments in Cloud Bigtable RestoreTable API to reflect the new API capability
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BaseBigtableTableAdminClient.java
  grpc-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/BigtableTableAdminGrpc.java
  proto-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/RestoreTableRequest.java
  proto-google-cloud-bigtable-admin-v2/src/main/java/com/google/bigtable/admin/v2/RestoreTableRequestOrBuilder.java
  proto-google-cloud-bigtable-admin-v2/src/main/proto/google/bigtable/admin/v2/bigtable_table_admin.proto
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#809 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#810 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#806 chore(test): log resource prefix to make debugging easier
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableBackupIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableCmekIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableInstanceAdminClientIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/it/BigtableTableAdminClientIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/AbstractTestEnv.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/PrefixGenerator.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java
Labels: api: bigtable, cla: yes

#812 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#813 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#815 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#817 chore: update cloud-rad doclet
  .kokoro/release/publish_javadoc11.sh
  pom.xml
Labels: api: bigtable, cla: yes

#827 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#828 build: configure branch 1.22.0-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigtable, cla: yes

#829 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: bigtable, automerge, cla: yes

#833 fix: add back in extraFiles and fix file path
  .github/release-please.yml
Labels: api: bigtable, automerge, cla: yes

#834 chore: synthtool template regen
  .kokoro/build.sh
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: partial

#835 fix: filter limit constant (#787)
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Query.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/QueryTest.java
Labels: api: bigtable, cla: yes

#832 fix: improve embedded version handling (#715)
  .github/release-please.yml
  google-cloud-bigtable/pom.xml
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/VersionTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java
  synth.py
Labels: api: bigtable, cla: yes

#840 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigtable, automerge, cla: yes

#845 fix: exclude protobuf from conformance-tests
  google-cloud-bigtable/pom.xml
  pom.xml
Labels: api: bigtable, cla: yes
