Repository googleapis/java-bigtable, pull requests merged in 2022-01, with the labels that each got.

#1052 fix: align ip version preference for the wrapped emulator
  google-cloud-bigtable-emulator/src/main/java/com/google/cloud/bigtable/emulator/v2/Emulator.java
Labels: cla: yes, api: bigtable

#1118 fix: Revert "fix: remove stats from javadoc"
  pom.xml
Labels: api: bigtable, automerge

#1130 chore: fix emulator bundling for 2.2.x sp
  .kokoro/build.sh
  google-cloud-bigtable-emulator/pom.xml
Labels: api: bigtable

#1129 chore: fix emulator bundling for 1.22.0 sp
  .kokoro/build.sh
  google-cloud-bigtable-emulator/pom.xml
Labels: api: bigtable, automerge

#1133 chore(java): update variable name to api_shortname in README template
  .kokoro/build.sh
  synth.metadata
Labels: api: bigtable, context: full

#1081 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  README.md
  google-cloud-bigtable-bom/pom.xml
  google-cloud-bigtable/pom.xml
  owlbot.py
  pom.xml
  samples/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
  samples/snippets/src/main/java/com/example/bigtable/Filters.java
  samples/snippets/src/main/java/com/example/bigtable/InstanceAdminExample.java
  samples/snippets/src/main/java/com/example/bigtable/Quickstart.java
  samples/snippets/src/main/java/com/example/bigtable/Reads.java
  samples/snippets/src/main/java/com/example/bigtable/TableAdminExample.java
  samples/snippets/src/test/java/com/example/bigtable/BigtableBaseTest.java
  samples/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
  samples/snippets/src/test/java/com/example/bigtable/InstanceAdminExampleTest.java
  samples/snippets/src/test/java/com/example/bigtable/MobileTimeSeriesBaseTest.java
  samples/snippets/src/test/java/com/example/bigtable/QuickstartTest.java
  samples/snippets/src/test/java/com/example/bigtable/ReadsTest.java
  samples/snippets/src/test/java/com/example/bigtable/TableAdminExampleTest.java
  synth.py
Labels: cla: yes, api: bigtable, automerge

#1137 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: api: bigtable, automerge, owlbot:ignore

#1096 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: api: bigtable

#1141 chore: update cloud rad doclet
  pom.xml
Labels: api: bigtable, automerge

#1142 fix: UpdateAppProfileRequest equals and hashcode should build proto
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/models/UpdateAppProfileRequest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/admin/v2/models/AppProfileTest.java
Labels: api: bigtable

#1151 build(fix): fix formatting to update versions properly
  pom.xml
Labels: api: bigtable, automerge
