Repository googleapis/java-bigtable, pull requests merged in 2022-11, with the labels that each got.

#1465 chore: add internal api for row merging
  README.md
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/internal/RowMergerUtil.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/DefaultRowAdapter.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/internal/RowMergerUtilTest.java
Labels: api: bigtable, automerge, size: m

#1492 chore: Fix the cloud bigtable link in readme
  .readme-partials.yml
  README.md
Labels: api: bigtable, automerge, size: xs

#1401 fix: fix the connectivity error count caculation
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerStreamingCallable.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerUnaryCallable.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/metrics/Util.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
Labels: api: bigtable, automerge, size: m

#1503 chore: turn off fail-fast behavior to prevent cancellation of jobs
  .github/workflows/ci.yaml
Labels: api: bigtable, size: xs

#1509 fix: fix metric client settings
  README.md
  google-cloud-bigtable-stats/src/main/java/com/google/cloud/bigtable/stats/BigtableStackdriverStatsExporter.java
Labels: api: bigtable, automerge, size: xs

#1515 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: api: bigtable, size: m

#1514 feat: next release from main branch is 2.17.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigtable, size: s

#1526 chore: update readme to build the root directory first
  test-proxy/README.md
Labels: api: bigtable, size: xs

#1529 test(fix): update the test proxy to set app profile id and connect to emulator correctly
  test-proxy/src/main/java/com/google/cloud/bigtable/testproxy/CbtTestProxy.java
  test-proxy/src/main/proto/v2_test_proxy.proto
Labels: api: bigtable, automerge, size: s

#1531 deps: update dependency com.google.cloud:google-cloud-monitoring-bom …
  google-cloud-bigtable-deps-bom/pom.xml
  google-cloud-bigtable-stats/pom.xml
  google-cloud-bigtable/pom.xml
Labels: api: bigtable, automerge, size: s

#1534 chore: update native image checks to use graalvm-22.3.0
  .kokoro/presubmit/graalvm-native-17.cfg
  .kokoro/presubmit/graalvm-native.cfg
Labels: api: bigtable, automerge, size: xs
