Repository googleapis/java-bigtable, pull requests merged in 2023-07, with the labels that each got.

#1808 fix: fix batch mutation limit
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/BulkMutation.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowMutationEntry.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchResource.java
  google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptor.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/BulkMutateIT.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/BulkMutationTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptorTest.java
Labels: api: bigtable, automerge, size: m

#1852 chore: setup 2.23.x lts branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
  README.md
Labels: api: bigtable, size: s

#1853 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/conformance.yaml
Labels: api: bigtable, size: m

#1857 fix: remove javadoc external link configuration (#1815)
  pom.xml
Labels: api: bigtable, owlbot:ignore, size: xs

#1860 chore: remove owlbot checks from non main branches
  .github/sync-repo-settings.yaml
Labels: api: bigtable, automerge, size: xs

#1863 chore: Add code formatting instructions to CONTRIBUTING
  CONTRIBUTING.md
Labels: api: bigtable, automerge, size: xs

#1865 chore: Fix flaky metrics tests
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BigtableTracerCallableTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/BuiltinMetricsTracerTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java
  google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/SimpleStatsComponent.java
Labels: api: bigtable, automerge, size: m

#1866 feat: setup 2.25.x lts branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigtable, size: s

#1867 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/conformance.yaml
Labels: api: bigtable, size: m
